SnakeSite/App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.change_desc_pic, name='change_profile'),
    path('add_profile/', views.add_desc_pic, name='add_profile'),
    path('edit_info/', views.edit_information, name='edit_info'),
    path('change_pass/', views.change_pass, name='change_pass'),
]

SnakeSite/Game_App/urls.py
from django.urls import path
from . import views

app_name = 'Game_App'

urlpatterns = [
    path('game/', views.game_event, name='game_event'),
    path('game_page/', views.game_page, name='game_page'),
    path('playing/', views.play, name='play'),
]

SnakeSite/snakesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('playing/', include('Game_App.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SnakeSite/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


class gameUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='game_user')
    profile_pic = models.ImageField(upload_to='profile_pics')
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.user

SnakeSite/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User
from .models import gameUser


class Sign_Up_Form(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class edit_info(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class change_description_pic(forms.ModelForm):
    class Meta:
        model = gameUser
        fields = ['description', 'profile_pic']

SnakeSite/App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import Sign_Up_Form, edit_info,change_description_pic
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from Game_App.models import record


# Create your views here.


def home(request):
    records = record.objects.all()[:10]
    return render(request, 'App_Login/home.html', context={'records': records})


def sign_up(request):
    form = Sign_Up_Form()
    signed_up = False
    if request.method == 'POST':
        form = Sign_Up_Form(request.POST)
        if form.is_valid():
            form.save()
            signed_up = True
    diction = {'form': form, 'signed_up': signed_up}
    return render(request, 'App_Login/sign_up.html', context=diction)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Login:home'))
    diction = {'form': form}
    return render(request, 'App_Login/login.html', context=diction)


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:home'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html',context={})


@login_required
def edit_information(request):
    current_user = request.user
    form = edit_info(instance=current_user)
    if request.method == 'POST':
        form = edit_info(instance=current_user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/edit_info.html', context={'form': form})


@login_required
def change_pass(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    diction = {'form':form}
    return render(request, 'App_Login/change_pass.html', context=diction)


@login_required
def add_desc_pic(request):
    current_user = request.user
    form = change_description_pic()
    if request.method == 'POST':
        form = change_description_pic(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_info = form.save(commit=False)
            new_info.user = current_user
            new_info.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/change_profile.html', context={'form': form})


@login_required
def change_desc_pic(request):
    current_user = request.user
    form = change_description_pic(instance=current_user.game_user)
    if request.method == 'POST':
        form = change_description_pic(instance=current_user.game_user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/change_profile.html', context={'form': form})

SnakeSite/templates/App_Login/change_pass.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}
    change pass
{%endblock%}
{%block body_block%}
    <form method="POST">
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary btn-sm" value="change">
    </form>
{%endblock%}

SnakeSite/templates/App_Login/change_profile.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}
    change profile
{%endblock%}
{%block body_block%}
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary btn-sm" value="submit">
    </form>
{%endblock%}

SnakeSite/templates/App_Login/edit_info.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}
    edit information
{%endblock%}
{%block body_block%}
    <form method="POST">
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary btn-sm" value="submit">
    </form>
<p> to change pass click<a href="{%url 'App_Login:change_pass'%}">here</a></p>
{%endblock%}

SnakeSite/templates/App_Login/home.html
{%extends 'base.html'%}
{%block title%}
    Home
{%endblock%}
{%block body_block%}
{%if user.is_authenticated%}
    <p> well come {{user.username}}</p>
{%endif%}
{%endblock%}

SnakeSite/templates/App_Login/login.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}
    login
{%endblock%}
{%block body_block%}
    <form method="POST">
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary btn-sm" value="login">
    </form>
{%endblock%}

SnakeSite/templates/App_Login/profile.html
{%extends 'base.html'%}
{%block title%}
    profile
{%endblock%}
{%block body_block%}
    <div class="row">
        <div class="col-sm-8">
            {%if user.game_user%}
                 <img src="/media/{{user.game_user.profile_pic}}" class="rounded-circle" width="25%">
                 <p>
                     {{user.game_user.description}}
                 </p>
                <a href="{%url 'App_Login:change_profile'%}"  class="btn btn-primary btn-sm"> change profile </a>
            {%else%}
                 <img src="/media/luffy.jfif" class="rounded-circle"  width="25%">
                 <div>
                     <br/>
                     ...
                     you better pull some description 😅
                     ...
                     <br/>
                 </div>
            <br/>
                <a href="{%url 'App_Login:add_profile'%}" class="btn btn-primary btn-sm"> add profile </a>
            {%endif%}
        </div>
        <div class="col-sm-4">
            <p>you entered as:</p>
            <p>
                {{user.username}}<br/>
            </p>
            <a href="{%url 'App_Login:edit_info'%}" class="btn btn-primary btn-sm"> edit info </a>
        </div>
    </div>
{%endblock%}

SnakeSite/templates/App_Login/sign_up.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}
    sign up
{%endblock%}
{%block body_block%}
{%if signed_up%}
<div class="alert alert-success"> you signed up successfully </div>
{%else%}
    <form method="POST">
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary btn-sm" value="submit">
    </form>
{%endif%}
{%endblock%}