SnakeSite/App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.change_desc_pic, name='change_profile'),
    path('add_profile/', views.add_desc_pic, name='add_profile'),
    path('edit_info/', views.edit_information, name='edit_info'),
    path('change_pass/', views.change_pass, name='change_pass'),
]

SnakeSite/Game_App/urls.py
from django.urls import path
from . import views

app_name = 'Game_App'

urlpatterns = [
    path('game/', views.game_event, name='game_event'),
    path('game_page/', views.game_page, name='game_page'),
    path('playing/', views.play, name='play'),
]

SnakeSite/snakesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('playing/', include('Game_App.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SnakeSite/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <title>
        {%block title%}
        {%endblock%}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar nav">
          <li class="nav-item active">
            <a href="{% url 'App_Login:home'%}" class="nav-link">home</a>
          </li>
          {%if user.is_authenticated%}
          <li class="nav-item active">
            <a href="{% url 'App_Login:profile'%}" class="nav-link">profile</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'App_Login:logout'%}" class="nav-link">logout</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'Game_App:play'%}" class="nav-link">play</a>
          </li>
          {%else%}
          <li class="nav-item active">
            <a href="{% url 'App_Login:sign_up'%}" class="nav-link">signup</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'App_Login:login'%}" class="nav-link">login</a>
          </li>
          {%endif%}

        </ul>
    </nav>
    <div class="container" style="padding-top:20px">
    {%block body_block%}
    {%endblock%}
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>